/* GENERATED FILE — DO NOT EDIT BY HAND.
 * Source: models.dev (https://models.dev/api.json); regenerate with `npm run models:refresh`.
 *
 * Which reasoning efforts an endpoint accepts, keyed `<catalog-provider>/<model-id>`. The value is the
 * accepted effort ladder, `true` for a model that reasons but exposes no effort knob (a bare toggle), or
 * `false` for one that does not reason at all. Consumed by descriptorCapabilities() in
 * modelCapabilities.ts, which is the only reader — a miss there falls back to name heuristics.
 *
 * 777 models, 473 of them reasoning-capable.
 */
import type { ModelThinkingLevel } from '@earendil-works/pi-ai';

/** Accepted effort ladder, `true` (reasons, effort not settable), or `false` (no reasoning). */
export type CatalogCapability = readonly ModelThinkingLevel[] | boolean;

export const MODEL_CAPABILITY_CATALOG: Readonly<Record<string, CatalogCapability>> = {
  'openai/chatgpt-image-latest': false,
  'openai/gpt-3.5-turbo': false,
  'openai/gpt-4': false,
  'openai/gpt-4-turbo': false,
  'openai/gpt-4.1': false,
  'openai/gpt-4.1-mini': false,
  'openai/gpt-4.1-nano': false,
  'openai/gpt-4o': false,
  'openai/gpt-4o-2024-05-13': false,
  'openai/gpt-4o-2024-08-06': false,
  'openai/gpt-4o-2024-11-20': false,
  'openai/gpt-4o-mini': false,
  'openai/gpt-5': ['minimal', 'low', 'medium', 'high'],
  'openai/gpt-5-chat-latest': true,
  'openai/gpt-5-codex': ['low', 'medium', 'high'],
  'openai/gpt-5-mini': ['minimal', 'low', 'medium', 'high'],
  'openai/gpt-5-nano': ['minimal', 'low', 'medium', 'high'],
  'openai/gpt-5-pro': ['high'],
  'openai/gpt-5.1': ['low', 'medium', 'high'],
  'openai/gpt-5.1-chat-latest': ['medium'],
  'openai/gpt-5.1-codex': ['low', 'medium', 'high'],
  'openai/gpt-5.1-codex-max': ['low', 'medium', 'high', 'xhigh'],
  'openai/gpt-5.1-codex-mini': ['low', 'medium', 'high'],
  'openai/gpt-5.2': ['low', 'medium', 'high', 'xhigh'],
  'openai/gpt-5.2-chat-latest': ['medium'],
  'openai/gpt-5.2-codex': ['low', 'medium', 'high', 'xhigh'],
  'openai/gpt-5.2-pro': ['medium', 'high', 'xhigh'],
  'openai/gpt-5.3-chat-latest': false,
  'openai/gpt-5.3-codex': ['low', 'medium', 'high', 'xhigh'],
  'openai/gpt-5.3-codex-spark': ['low', 'medium', 'high', 'xhigh'],
  'openai/gpt-5.4': ['low', 'medium', 'high', 'xhigh'],
  'openai/gpt-5.4-mini': ['low', 'medium', 'high', 'xhigh'],
  'openai/gpt-5.4-nano': ['low', 'medium', 'high', 'xhigh'],
  'openai/gpt-5.4-pro': ['medium', 'high', 'xhigh'],
  'openai/gpt-5.5': ['low', 'medium', 'high', 'xhigh'],
  'openai/gpt-5.5-pro': ['medium', 'high', 'xhigh'],
  'openai/gpt-5.6': ['low', 'medium', 'high', 'xhigh', 'max'],
  'openai/gpt-5.6-luna': ['low', 'medium', 'high', 'xhigh', 'max'],
  'openai/gpt-5.6-sol': ['low', 'medium', 'high', 'xhigh', 'max'],
  'openai/gpt-5.6-terra': ['low', 'medium', 'high', 'xhigh', 'max'],
  'openai/gpt-image-1': false,
  'openai/gpt-image-1-mini': false,
  'openai/gpt-image-1.5': false,
  'openai/gpt-image-2': false,
  'openai/gpt-realtime-2.1': ['minimal', 'low', 'medium', 'high', 'xhigh'],
  'openai/o1': ['low', 'medium', 'high'],
  'openai/o1-pro': ['low', 'medium', 'high'],
  'openai/o3': ['low', 'medium', 'high'],
  'openai/o3-deep-research': ['medium'],
  'openai/o3-mini': ['low', 'medium', 'high'],
  'openai/o3-pro': ['low', 'medium', 'high'],
  'openai/o4-mini': ['low', 'medium', 'high'],
  'openai/o4-mini-deep-research': ['medium'],
  'openai/text-embedding-3-large': false,
  'openai/text-embedding-3-small': false,
  'openai/text-embedding-ada-002': false,
  'anthropic/claude-fable-5': ['low', 'medium', 'high', 'xhigh', 'max'],
  'anthropic/claude-haiku-4-5': true,
  'anthropic/claude-haiku-4-5-20251001': true,
  'anthropic/claude-opus-4-1': true,
  'anthropic/claude-opus-4-1-20250805': true,
  'anthropic/claude-opus-4-5': ['low', 'medium', 'high'],
  'anthropic/claude-opus-4-5-20251101': ['low', 'medium', 'high'],
  'anthropic/claude-opus-4-6': ['low', 'medium', 'high', 'max'],
  'anthropic/claude-opus-4-7': ['low', 'medium', 'high', 'xhigh', 'max'],
  'anthropic/claude-opus-4-8': ['low', 'medium', 'high', 'xhigh', 'max'],
  'anthropic/claude-sonnet-4-5': true,
  'anthropic/claude-sonnet-4-5-20250929': true,
  'anthropic/claude-sonnet-4-6': ['low', 'medium', 'high', 'max'],
  'anthropic/claude-sonnet-5': ['low', 'medium', 'high', 'xhigh', 'max'],
  'google/gemini-2.0-flash': false,
  'google/gemini-2.0-flash-lite': false,
  'google/gemini-2.5-flash': true,
  'google/gemini-2.5-flash-image': true,
  'google/gemini-2.5-flash-lite': true,
  'google/gemini-2.5-flash-preview-tts': false,
  'google/gemini-2.5-pro': true,
  'google/gemini-2.5-pro-preview-tts': false,
  'google/gemini-3-flash-preview': ['minimal', 'low', 'medium', 'high'],
  'google/gemini-3-pro-image-preview': true,
  'google/gemini-3-pro-preview': ['low', 'high'],
  'google/gemini-3.1-flash-image-preview': ['minimal', 'high'],
  'google/gemini-3.1-flash-lite': ['minimal', 'low', 'medium', 'high'],
  'google/gemini-3.1-flash-lite-preview': ['minimal', 'low', 'medium', 'high'],
  'google/gemini-3.1-pro-preview': ['low', 'medium', 'high'],
  'google/gemini-3.1-pro-preview-customtools': ['low', 'medium', 'high'],
  'google/gemini-3.5-flash': ['minimal', 'low', 'medium', 'high'],
  'google/gemini-embedding-001': false,
  'google/gemini-flash-latest': true,
  'google/gemini-flash-lite-latest': true,
  'google/gemini-omni-flash-preview': true,
  'google/gemma-4-26b-a4b-it': true,
  'google/gemma-4-31b-it': true,
  'openrouter/~anthropic/claude-fable-latest': ['low', 'medium', 'high', 'xhigh', 'max'],
  'openrouter/~anthropic/claude-haiku-latest': true,
  'openrouter/~anthropic/claude-opus-latest': ['low', 'medium', 'high', 'xhigh', 'max'],
  'openrouter/~anthropic/claude-sonnet-latest': ['low', 'medium', 'high', 'max'],
  'openrouter/~google/gemini-flash-latest': ['minimal', 'low', 'medium', 'high'],
  'openrouter/~google/gemini-pro-latest': ['low', 'medium', 'high'],
  'openrouter/~moonshotai/kimi-latest': true,
  'openrouter/~openai/gpt-latest': ['low', 'medium', 'high', 'xhigh'],
  'openrouter/~openai/gpt-mini-latest': ['low', 'medium', 'high', 'xhigh'],
  'openrouter/~x-ai/grok-latest': ['low', 'medium', 'high'],
  'openrouter/ai21/jamba-large-1.7': false,
  'openrouter/aion-labs/aion-2.0': true,
  'openrouter/aion-labs/aion-3.0': true,
  'openrouter/aion-labs/aion-3.0-mini': true,
  'openrouter/aion-labs/aion-rp-llama-3.1-8b': false,
  'openrouter/allenai/olmo-3-32b-think': true,
  'openrouter/amazon/nova-2-lite-v1': true,
  'openrouter/amazon/nova-lite-v1': false,
  'openrouter/amazon/nova-micro-v1': false,
  'openrouter/amazon/nova-premier-v1': false,
  'openrouter/amazon/nova-pro-v1': false,
  'openrouter/anthracite-org/magnum-v4-72b': false,
  'openrouter/anthropic/claude-3-haiku': false,
  'openrouter/anthropic/claude-fable-5': ['low', 'medium', 'high', 'xhigh', 'max'],
  'openrouter/anthropic/claude-haiku-4.5': true,
  'openrouter/anthropic/claude-opus-4': true,
  'openrouter/anthropic/claude-opus-4.1': true,
  'openrouter/anthropic/claude-opus-4.5': ['low', 'medium', 'high'],
  'openrouter/anthropic/claude-opus-4.6': ['low', 'medium', 'high', 'max'],
  'openrouter/anthropic/claude-opus-4.7': ['low', 'medium', 'high', 'xhigh', 'max'],
  'openrouter/anthropic/claude-opus-4.7-fast': ['low', 'medium', 'high', 'xhigh', 'max'],
  'openrouter/anthropic/claude-opus-4.8': ['low', 'medium', 'high', 'xhigh', 'max'],
  'openrouter/anthropic/claude-opus-4.8-fast': ['low', 'medium', 'high', 'xhigh', 'max'],
  'openrouter/anthropic/claude-sonnet-4': true,
  'openrouter/anthropic/claude-sonnet-4.5': true,
  'openrouter/anthropic/claude-sonnet-4.6': ['low', 'medium', 'high', 'max'],
  'openrouter/anthropic/claude-sonnet-5': ['low', 'medium', 'high', 'xhigh', 'max'],
  'openrouter/arcee-ai/coder-large': false,
  'openrouter/arcee-ai/trinity-large-thinking': true,
  'openrouter/arcee-ai/virtuoso-large': false,
  'openrouter/baidu/ernie-4.5-vl-424b-a47b': true,
  'openrouter/bytedance-seed/seed-1.6': true,
  'openrouter/bytedance-seed/seed-1.6-flash': true,
  'openrouter/bytedance-seed/seed-2.0-lite': ['minimal', 'low', 'medium', 'high'],
  'openrouter/bytedance-seed/seed-2.0-mini': ['minimal', 'low', 'medium', 'high'],
  'openrouter/bytedance/ui-tars-1.5-7b': false,
  'openrouter/cognitivecomputations/dolphin-mistral-24b-venice-edition': false,
  'openrouter/cognitivecomputations/dolphin-mistral-24b-venice-edition:free': false,
  'openrouter/cohere/command-a': false,
  'openrouter/cohere/command-r-08-2024': false,
  'openrouter/cohere/command-r-plus-08-2024': false,
  'openrouter/cohere/command-r7b-12-2024': false,
  'openrouter/cohere/north-mini-code:free': true,
  'openrouter/deepcogito/cogito-v2.1-671b': true,
  'openrouter/deepseek/deepseek-chat': false,
  'openrouter/deepseek/deepseek-chat-v3-0324': false,
  'openrouter/deepseek/deepseek-chat-v3.1': true,
  'openrouter/deepseek/deepseek-r1': true,
  'openrouter/deepseek/deepseek-r1-0528': true,
  'openrouter/deepseek/deepseek-r1-distill-llama-70b': true,
  'openrouter/deepseek/deepseek-v3.1-terminus': true,
  'openrouter/deepseek/deepseek-v3.2': true,
  'openrouter/deepseek/deepseek-v3.2-exp': true,
  'openrouter/deepseek/deepseek-v4-flash': ['high', 'xhigh'],
  'openrouter/deepseek/deepseek-v4-pro': ['high', 'xhigh'],
  'openrouter/google/gemini-2.5-flash': true,
  'openrouter/google/gemini-2.5-flash-image': false,
  'openrouter/google/gemini-2.5-flash-lite': true,
  'openrouter/google/gemini-2.5-pro': true,
  'openrouter/google/gemini-2.5-pro-preview': true,
  'openrouter/google/gemini-2.5-pro-preview-05-06': true,
  'openrouter/google/gemini-3-flash-preview': ['minimal', 'low', 'medium', 'high'],
  'openrouter/google/gemini-3-pro-image': true,
  'openrouter/google/gemini-3-pro-image-preview': true,
  'openrouter/google/gemini-3.1-flash-image': ['high', 'minimal'],
  'openrouter/google/gemini-3.1-flash-image-preview': ['minimal', 'high'],
  'openrouter/google/gemini-3.1-flash-lite': ['minimal', 'low', 'medium', 'high'],
  'openrouter/google/gemini-3.1-flash-lite-image': ['minimal', 'high'],
  'openrouter/google/gemini-3.1-flash-lite-preview': ['minimal', 'low', 'medium', 'high'],
  'openrouter/google/gemini-3.1-pro-preview': ['low', 'medium', 'high'],
  'openrouter/google/gemini-3.1-pro-preview-customtools': ['low', 'medium', 'high'],
  'openrouter/google/gemini-3.5-flash': ['minimal', 'low', 'medium', 'high'],
  'openrouter/google/gemma-2-27b-it': false,
  'openrouter/google/gemma-3-12b-it': false,
  'openrouter/google/gemma-3-27b-it': false,
  'openrouter/google/gemma-3-4b-it': false,
  'openrouter/google/gemma-3n-e4b-it': false,
  'openrouter/google/gemma-4-26b-a4b-it': true,
  'openrouter/google/gemma-4-26b-a4b-it:free': true,
  'openrouter/google/gemma-4-31b-it': true,
  'openrouter/google/gemma-4-31b-it:free': true,
  'openrouter/google/lyria-3-clip-preview': false,
  'openrouter/google/lyria-3-pro-preview': false,
  'openrouter/gryphe/mythomax-l2-13b': false,
  'openrouter/ibm-granite/granite-4.0-h-micro': false,
  'openrouter/ibm-granite/granite-4.1-8b': false,
  'openrouter/inception/mercury-2': ['low', 'medium', 'high'],
  'openrouter/inclusionai/ling-2.6-1t': false,
  'openrouter/inclusionai/ling-2.6-flash': false,
  'openrouter/inclusionai/ring-2.6-1t': ['high', 'xhigh'],
  'openrouter/inflection/inflection-3-pi': false,
  'openrouter/inflection/inflection-3-productivity': false,
  'openrouter/kwaipilot/kat-coder-pro-v2': false,
  'openrouter/liquid/lfm-2.5-1.2b-instruct:free': false,
  'openrouter/liquid/lfm-2.5-1.2b-thinking:free': true,
  'openrouter/mancer/weaver': false,
  'openrouter/meta-llama/llama-3-8b-instruct': false,
  'openrouter/meta-llama/llama-3.1-70b-instruct': false,
  'openrouter/meta-llama/llama-3.1-8b-instruct': false,
  'openrouter/meta-llama/llama-3.2-11b-vision-instruct': false,
  'openrouter/meta-llama/llama-3.2-1b-instruct': false,
  'openrouter/meta-llama/llama-3.2-3b-instruct': false,
  'openrouter/meta-llama/llama-3.2-3b-instruct:free': false,
  'openrouter/meta-llama/llama-3.3-70b-instruct': false,
  'openrouter/meta-llama/llama-3.3-70b-instruct:free': false,
  'openrouter/meta-llama/llama-4-maverick': false,
  'openrouter/meta-llama/llama-4-scout': false,
  'openrouter/meta-llama/llama-guard-4-12b': false,
  'openrouter/microsoft/phi-4': false,
  'openrouter/microsoft/wizardlm-2-8x22b': false,
  'openrouter/minimax/minimax-01': false,
  'openrouter/minimax/minimax-m1': true,
  'openrouter/minimax/minimax-m2': true,
  'openrouter/minimax/minimax-m2-her': false,
  'openrouter/minimax/minimax-m2.1': true,
  'openrouter/minimax/minimax-m2.5': true,
  'openrouter/minimax/minimax-m2.7': true,
  'openrouter/minimax/minimax-m3': true,
  'openrouter/mistralai/codestral-2508': false,
  'openrouter/mistralai/devstral-2512': false,
  'openrouter/mistralai/ministral-14b-2512': false,
  'openrouter/mistralai/ministral-3b-2512': false,
  'openrouter/mistralai/ministral-8b-2512': false,
  'openrouter/mistralai/mistral-large': false,
  'openrouter/mistralai/mistral-large-2407': false,
  'openrouter/mistralai/mistral-large-2512': false,
  'openrouter/mistralai/mistral-medium-3': false,
  'openrouter/mistralai/mistral-medium-3-5': ['high'],
  'openrouter/mistralai/mistral-medium-3.1': false,
  'openrouter/mistralai/mistral-nemo': false,
  'openrouter/mistralai/mistral-saba': false,
  'openrouter/mistralai/mistral-small-24b-instruct-2501': false,
  'openrouter/mistralai/mistral-small-2603': ['high'],
  'openrouter/mistralai/mistral-small-3.1-24b-instruct': false,
  'openrouter/mistralai/mistral-small-3.2-24b-instruct': false,
  'openrouter/mistralai/mixtral-8x22b-instruct': false,
  'openrouter/mistralai/voxtral-small-24b-2507': false,
  'openrouter/moonshotai/kimi-k2': false,
  'openrouter/moonshotai/kimi-k2-0905': false,
  'openrouter/moonshotai/kimi-k2-thinking': true,
  'openrouter/moonshotai/kimi-k2.5': true,
  'openrouter/moonshotai/kimi-k2.6': true,
  'openrouter/moonshotai/kimi-k2.7-code': true,
  'openrouter/morph/morph-v3-fast': false,
  'openrouter/morph/morph-v3-large': false,
  'openrouter/nex-agi/nex-n2-mini': true,
  'openrouter/nex-agi/nex-n2-pro': true,
  'openrouter/nousresearch/hermes-3-llama-3.1-405b': false,
  'openrouter/nousresearch/hermes-3-llama-3.1-405b:free': false,
  'openrouter/nousresearch/hermes-3-llama-3.1-70b': false,
  'openrouter/nousresearch/hermes-4-405b': true,
  'openrouter/nousresearch/hermes-4-70b': true,
  'openrouter/nvidia/llama-3.3-nemotron-super-49b-v1.5': true,
  'openrouter/nvidia/nemotron-3-nano-30b-a3b': true,
  'openrouter/nvidia/nemotron-3-nano-30b-a3b:free': true,
  'openrouter/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free': true,
  'openrouter/nvidia/nemotron-3-super-120b-a12b': ['low', 'medium'],
  'openrouter/nvidia/nemotron-3-super-120b-a12b:free': ['low', 'medium'],
  'openrouter/nvidia/nemotron-3-ultra-550b-a55b': ['medium', 'high'],
  'openrouter/nvidia/nemotron-3-ultra-550b-a55b:free': ['medium', 'high'],
  'openrouter/nvidia/nemotron-3.5-content-safety:free': true,
  'openrouter/nvidia/nemotron-nano-12b-v2-vl:free': true,
  'openrouter/nvidia/nemotron-nano-9b-v2:free': true,
  'openrouter/openai/gpt-3.5-turbo': false,
  'openrouter/openai/gpt-3.5-turbo-0613': false,
  'openrouter/openai/gpt-3.5-turbo-16k': false,
  'openrouter/openai/gpt-3.5-turbo-instruct': false,
  'openrouter/openai/gpt-4': false,
  'openrouter/openai/gpt-4-turbo': false,
  'openrouter/openai/gpt-4-turbo-preview': false,
  'openrouter/openai/gpt-4.1': false,
  'openrouter/openai/gpt-4.1-mini': false,
  'openrouter/openai/gpt-4.1-nano': false,
  'openrouter/openai/gpt-4o': false,
  'openrouter/openai/gpt-4o-2024-05-13': false,
  'openrouter/openai/gpt-4o-2024-08-06': false,
  'openrouter/openai/gpt-4o-2024-11-20': false,
  'openrouter/openai/gpt-4o-mini': false,
  'openrouter/openai/gpt-4o-mini-2024-07-18': false,
  'openrouter/openai/gpt-4o-mini-search-preview': false,
  'openrouter/openai/gpt-4o-search-preview': false,
  'openrouter/openai/gpt-5': ['minimal', 'low', 'medium', 'high'],
  'openrouter/openai/gpt-5-chat': false,
  'openrouter/openai/gpt-5-codex': ['low', 'medium', 'high'],
  'openrouter/openai/gpt-5-image': true,
  'openrouter/openai/gpt-5-image-mini': true,
  'openrouter/openai/gpt-5-mini': ['minimal', 'low', 'medium', 'high'],
  'openrouter/openai/gpt-5-nano': ['minimal', 'low', 'medium', 'high'],
  'openrouter/openai/gpt-5-pro': ['high'],
  'openrouter/openai/gpt-5.1': ['low', 'medium', 'high'],
  'openrouter/openai/gpt-5.1-chat': false,
  'openrouter/openai/gpt-5.1-codex': ['low', 'medium', 'high'],
  'openrouter/openai/gpt-5.1-codex-max': ['low', 'medium', 'high', 'xhigh'],
  'openrouter/openai/gpt-5.1-codex-mini': ['low', 'medium', 'high'],
  'openrouter/openai/gpt-5.2': ['low', 'medium', 'high', 'xhigh'],
  'openrouter/openai/gpt-5.2-chat': false,
  'openrouter/openai/gpt-5.2-codex': ['low', 'medium', 'high', 'xhigh'],
  'openrouter/openai/gpt-5.2-pro': ['medium', 'high', 'xhigh'],
  'openrouter/openai/gpt-5.3-chat': false,
  'openrouter/openai/gpt-5.3-codex': ['low', 'medium', 'high', 'xhigh'],
  'openrouter/openai/gpt-5.4': ['low', 'medium', 'high', 'xhigh'],
  'openrouter/openai/gpt-5.4-image-2': ['low', 'medium', 'high', 'xhigh'],
  'openrouter/openai/gpt-5.4-mini': ['low', 'medium', 'high', 'xhigh'],
  'openrouter/openai/gpt-5.4-nano': ['low', 'medium', 'high', 'xhigh'],
  'openrouter/openai/gpt-5.4-pro': ['medium', 'high', 'xhigh'],
  'openrouter/openai/gpt-5.5': ['low', 'medium', 'high', 'xhigh'],
  'openrouter/openai/gpt-5.5-pro': ['medium', 'high', 'xhigh'],
  'openrouter/openai/gpt-5.6-luna': ['low', 'medium', 'high', 'xhigh', 'max'],
  'openrouter/openai/gpt-5.6-luna-pro': ['low', 'medium', 'high', 'xhigh', 'max'],
  'openrouter/openai/gpt-5.6-sol': ['low', 'medium', 'high', 'xhigh', 'max'],
  'openrouter/openai/gpt-5.6-sol-pro': ['low', 'medium', 'high', 'xhigh', 'max'],
  'openrouter/openai/gpt-5.6-terra': ['low', 'medium', 'high', 'xhigh', 'max'],
  'openrouter/openai/gpt-5.6-terra-pro': ['low', 'medium', 'high', 'xhigh', 'max'],
  'openrouter/openai/gpt-audio': false,
  'openrouter/openai/gpt-audio-mini': false,
  'openrouter/openai/gpt-chat-latest': false,
  'openrouter/openai/gpt-oss-120b': ['low', 'medium', 'high'],
  'openrouter/openai/gpt-oss-120b:free': ['low', 'medium', 'high'],
  'openrouter/openai/gpt-oss-20b': ['low', 'medium', 'high'],
  'openrouter/openai/gpt-oss-20b:free': ['low', 'medium', 'high'],
  'openrouter/openai/gpt-oss-safeguard-20b': ['low', 'medium', 'high'],
  'openrouter/openai/o1': ['low', 'medium', 'high'],
  'openrouter/openai/o1-pro': true,
  'openrouter/openai/o3': ['low', 'medium', 'high'],
  'openrouter/openai/o3-deep-research': true,
  'openrouter/openai/o3-mini': ['low', 'medium', 'high'],
  'openrouter/openai/o3-mini-high': ['high'],
  'openrouter/openai/o3-pro': ['low', 'medium', 'high'],
  'openrouter/openai/o4-mini': ['low', 'medium', 'high'],
  'openrouter/openai/o4-mini-deep-research': true,
  'openrouter/openai/o4-mini-high': ['high'],
  'openrouter/openrouter/auto': true,
  'openrouter/openrouter/bodybuilder': false,
  'openrouter/openrouter/free': true,
  'openrouter/openrouter/fusion': false,
  'openrouter/openrouter/pareto-code': false,
  'openrouter/perceptron/perceptron-mk1': true,
  'openrouter/perplexity/sonar': false,
  'openrouter/perplexity/sonar-deep-research': true,
  'openrouter/perplexity/sonar-pro': false,
  'openrouter/perplexity/sonar-pro-search': true,
  'openrouter/perplexity/sonar-reasoning-pro': true,
  'openrouter/poolside/laguna-m.1': true,
  'openrouter/poolside/laguna-m.1:free': true,
  'openrouter/poolside/laguna-xs-2.1': true,
  'openrouter/poolside/laguna-xs-2.1:free': true,
  'openrouter/qwen/qwen-2.5-72b-instruct': false,
  'openrouter/qwen/qwen-2.5-7b-instruct': false,
  'openrouter/qwen/qwen-2.5-coder-32b-instruct': false,
  'openrouter/qwen/qwen-plus': false,
  'openrouter/qwen/qwen-plus-2025-07-28': false,
  'openrouter/qwen/qwen-plus-2025-07-28:thinking': true,
  'openrouter/qwen/qwen2.5-vl-72b-instruct': false,
  'openrouter/qwen/qwen3-14b': true,
  'openrouter/qwen/qwen3-235b-a22b': true,
  'openrouter/qwen/qwen3-235b-a22b-2507': false,
  'openrouter/qwen/qwen3-235b-a22b-thinking-2507': true,
  'openrouter/qwen/qwen3-30b-a3b': true,
  'openrouter/qwen/qwen3-30b-a3b-instruct-2507': false,
  'openrouter/qwen/qwen3-30b-a3b-thinking-2507': true,
  'openrouter/qwen/qwen3-32b': true,
  'openrouter/qwen/qwen3-8b': true,
  'openrouter/qwen/qwen3-coder': false,
  'openrouter/qwen/qwen3-coder-30b-a3b-instruct': false,
  'openrouter/qwen/qwen3-coder-flash': false,
  'openrouter/qwen/qwen3-coder-next': false,
  'openrouter/qwen/qwen3-coder-plus': false,
  'openrouter/qwen/qwen3-coder:free': false,
  'openrouter/qwen/qwen3-max': false,
  'openrouter/qwen/qwen3-max-thinking': true,
  'openrouter/qwen/qwen3-next-80b-a3b-instruct': false,
  'openrouter/qwen/qwen3-next-80b-a3b-instruct:free': false,
  'openrouter/qwen/qwen3-next-80b-a3b-thinking': true,
  'openrouter/qwen/qwen3-vl-235b-a22b-instruct': false,
  'openrouter/qwen/qwen3-vl-235b-a22b-thinking': true,
  'openrouter/qwen/qwen3-vl-30b-a3b-instruct': false,
  'openrouter/qwen/qwen3-vl-30b-a3b-thinking': true,
  'openrouter/qwen/qwen3-vl-32b-instruct': false,
  'openrouter/qwen/qwen3-vl-8b-instruct': false,
  'openrouter/qwen/qwen3-vl-8b-thinking': true,
  'openrouter/qwen/qwen3.5-122b-a10b': true,
  'openrouter/qwen/qwen3.5-27b': true,
  'openrouter/qwen/qwen3.5-35b-a3b': true,
  'openrouter/qwen/qwen3.5-397b-a17b': true,
  'openrouter/qwen/qwen3.5-9b': true,
  'openrouter/qwen/qwen3.5-flash-02-23': true,
  'openrouter/qwen/qwen3.5-plus-02-15': true,
  'openrouter/qwen/qwen3.5-plus-20260420': true,
  'openrouter/qwen/qwen3.6-27b': true,
  'openrouter/qwen/qwen3.6-35b-a3b': true,
  'openrouter/qwen/qwen3.6-flash': true,
  'openrouter/qwen/qwen3.6-max-preview': true,
  'openrouter/qwen/qwen3.6-plus': true,
  'openrouter/qwen/qwen3.7-max': true,
  'openrouter/qwen/qwen3.7-plus': true,
  'openrouter/rekaai/reka-edge': false,
  'openrouter/rekaai/reka-flash-3': true,
  'openrouter/relace/relace-apply-3': false,
  'openrouter/relace/relace-search': false,
  'openrouter/sakana/fugu-ultra': ['max', 'xhigh', 'high'],
  'openrouter/sao10k/l3-lunaris-8b': false,
  'openrouter/sao10k/l3.1-70b-hanami-x1': false,
  'openrouter/sao10k/l3.1-euryale-70b': false,
  'openrouter/sao10k/l3.3-euryale-70b': false,
  'openrouter/stepfun/step-3.5-flash': true,
  'openrouter/stepfun/step-3.7-flash': ['low', 'medium', 'high'],
  'openrouter/tencent/hunyuan-a13b-instruct': true,
  'openrouter/tencent/hy3': ['low', 'high'],
  'openrouter/tencent/hy3-preview': ['low', 'high'],
  'openrouter/tencent/hy3:free': ['low', 'high'],
  'openrouter/thedrummer/cydonia-24b-v4.1': false,
  'openrouter/thedrummer/rocinante-12b': false,
  'openrouter/thedrummer/skyfall-36b-v2': false,
  'openrouter/thedrummer/unslopnemo-12b': false,
  'openrouter/undi95/remm-slerp-l2-13b': false,
  'openrouter/upstage/solar-pro-3': true,
  'openrouter/writer/palmyra-x5': false,
  'openrouter/x-ai/grok-4.20': true,
  'openrouter/x-ai/grok-4.20-multi-agent': ['low', 'high'],
  'openrouter/x-ai/grok-4.3': ['low', 'medium', 'high'],
  'openrouter/x-ai/grok-4.5': ['low', 'medium', 'high'],
  'openrouter/x-ai/grok-build-0.1': true,
  'openrouter/xiaomi/mimo-v2.5': true,
  'openrouter/xiaomi/mimo-v2.5-pro': true,
  'openrouter/z-ai/glm-4.5': true,
  'openrouter/z-ai/glm-4.5-air': true,
  'openrouter/z-ai/glm-4.5v': true,
  'openrouter/z-ai/glm-4.6': true,
  'openrouter/z-ai/glm-4.6v': true,
  'openrouter/z-ai/glm-4.7': true,
  'openrouter/z-ai/glm-4.7-flash': true,
  'openrouter/z-ai/glm-5': true,
  'openrouter/z-ai/glm-5-turbo': true,
  'openrouter/z-ai/glm-5.1': true,
  'openrouter/z-ai/glm-5.2': ['high', 'xhigh'],
  'openrouter/z-ai/glm-5v-turbo': true,
  'xai/grok-4.20-0309-non-reasoning': false,
  'xai/grok-4.20-0309-reasoning': true,
  'xai/grok-4.20-multi-agent-0309': ['low', 'medium', 'high', 'xhigh'],
  'xai/grok-4.3': ['low', 'medium', 'high'],
  'xai/grok-4.5': ['low', 'medium', 'high'],
  'xai/grok-build-0.1': true,
  'xai/grok-imagine-image': false,
  'xai/grok-imagine-image-quality': false,
  'xai/grok-imagine-video': false,
  'deepseek/deepseek-chat': false,
  'deepseek/deepseek-reasoner': true,
  'deepseek/deepseek-v4-flash': ['high', 'max'],
  'deepseek/deepseek-v4-pro': ['high', 'max'],
  'groq/canopylabs/orpheus-arabic-saudi': false,
  'groq/canopylabs/orpheus-v1-english': false,
  'groq/groq/compound': false,
  'groq/groq/compound-mini': false,
  'groq/llama-3.1-8b-instant': false,
  'groq/llama-3.3-70b-versatile': false,
  'groq/meta-llama/llama-4-scout-17b-16e-instruct': false,
  'groq/meta-llama/llama-prompt-guard-2-22m': false,
  'groq/meta-llama/llama-prompt-guard-2-86m': false,
  'groq/openai/gpt-oss-120b': ['low', 'medium', 'high'],
  'groq/openai/gpt-oss-20b': ['low', 'medium', 'high'],
  'groq/openai/gpt-oss-safeguard-20b': ['low', 'medium', 'high'],
  'groq/qwen/qwen3-32b': true,
  'groq/whisper-large-v3': false,
  'groq/whisper-large-v3-turbo': false,
  'mistral/codestral-latest': false,
  'mistral/devstral-2512': false,
  'mistral/devstral-latest': false,
  'mistral/devstral-medium-2507': false,
  'mistral/devstral-medium-latest': false,
  'mistral/devstral-small-2505': false,
  'mistral/devstral-small-2507': false,
  'mistral/labs-devstral-small-2512': false,
  'mistral/magistral-medium-latest': true,
  'mistral/magistral-small': true,
  'mistral/ministral-3b-latest': false,
  'mistral/ministral-8b-latest': false,
  'mistral/mistral-embed': false,
  'mistral/mistral-large-2411': false,
  'mistral/mistral-large-2512': false,
  'mistral/mistral-large-latest': false,
  'mistral/mistral-medium-2505': false,
  'mistral/mistral-medium-2508': false,
  'mistral/mistral-medium-2604': ['high'],
  'mistral/mistral-medium-latest': ['high'],
  'mistral/mistral-nemo': false,
  'mistral/mistral-small-2506': false,
  'mistral/mistral-small-2603': ['high'],
  'mistral/mistral-small-latest': ['high'],
  'mistral/open-mistral-7b': false,
  'mistral/open-mistral-nemo': false,
  'mistral/open-mixtral-8x22b': false,
  'mistral/open-mixtral-8x7b': false,
  'mistral/pixtral-12b': false,
  'mistral/pixtral-large-latest': false,
  'cerebras/gemma-4-31b': ['low', 'medium', 'high'],
  'cerebras/gpt-oss-120b': ['low', 'medium', 'high'],
  'cerebras/zai-glm-4.7': true,
  'perplexity/sonar': false,
  'perplexity/sonar-deep-research': ['minimal', 'low', 'medium', 'high'],
  'perplexity/sonar-pro': false,
  'perplexity/sonar-reasoning-pro': ['minimal', 'low', 'medium', 'high'],
  'deepinfra/deepseek-ai/DeepSeek-R1-0528': true,
  'deepinfra/deepseek-ai/DeepSeek-V3.2': true,
  'deepinfra/deepseek-ai/DeepSeek-V4-Flash': ['low', 'medium', 'high', 'xhigh'],
  'deepinfra/deepseek-ai/DeepSeek-V4-Pro': ['low', 'medium', 'high', 'xhigh'],
  'deepinfra/google/gemma-4-26B-A4B-it': true,
  'deepinfra/google/gemma-4-31B-it': true,
  'deepinfra/meta-llama/Llama-3.3-70B-Instruct-Turbo': false,
  'deepinfra/meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8': false,
  'deepinfra/meta-llama/Llama-4-Scout-17B-16E-Instruct': false,
  'deepinfra/MiniMaxAI/MiniMax-M2.5': true,
  'deepinfra/MiniMaxAI/MiniMax-M2.7': true,
  'deepinfra/MiniMaxAI/MiniMax-M3': true,
  'deepinfra/moonshotai/Kimi-K2.5': true,
  'deepinfra/moonshotai/Kimi-K2.6': true,
  'deepinfra/moonshotai/Kimi-K2.7-Code': true,
  'deepinfra/nvidia/Llama-3.3-Nemotron-Super-49B-v1.5': true,
  'deepinfra/nvidia/Nemotron-3-Nano-30B-A3B': true,
  'deepinfra/nvidia/Nemotron-3-Nano-Omni-30B-A3B-Reasoning': true,
  'deepinfra/openai/gpt-oss-120b': ['low', 'medium', 'high'],
  'deepinfra/openai/gpt-oss-20b': ['low', 'medium', 'high'],
  'deepinfra/Qwen/Qwen3-32B': true,
  'deepinfra/Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo': false,
  'deepinfra/Qwen/Qwen3-Max': false,
  'deepinfra/Qwen/Qwen3-Next-80B-A3B-Instruct': false,
  'deepinfra/Qwen/Qwen3.5-122B-A10B': true,
  'deepinfra/Qwen/Qwen3.5-27B': true,
  'deepinfra/Qwen/Qwen3.5-35B-A3B': true,
  'deepinfra/Qwen/Qwen3.5-397B-A17B': true,
  'deepinfra/Qwen/Qwen3.5-9B': true,
  'deepinfra/Qwen/Qwen3.6-27B': true,
  'deepinfra/Qwen/Qwen3.6-35B-A3B': true,
  'deepinfra/Qwen/Qwen3.7-Max': false,
  'deepinfra/XiaomiMiMo/MiMo-V2.5': true,
  'deepinfra/XiaomiMiMo/MiMo-V2.5-Pro': true,
  'deepinfra/zai-org/GLM-4.6': true,
  'deepinfra/zai-org/GLM-4.7': true,
  'deepinfra/zai-org/GLM-4.7-Flash': true,
  'deepinfra/zai-org/GLM-5': true,
  'deepinfra/zai-org/GLM-5.1': true,
  'deepinfra/zai-org/GLM-5.2': ['low', 'medium', 'high', 'xhigh'],
  'zai/glm-4.5': true,
  'zai/glm-4.5-air': true,
  'zai/glm-4.5-flash': true,
  'zai/glm-4.5v': true,
  'zai/glm-4.6': true,
  'zai/glm-4.6v': true,
  'zai/glm-4.7': true,
  'zai/glm-4.7-flash': true,
  'zai/glm-4.7-flashx': true,
  'zai/glm-5': true,
  'zai/glm-5-turbo': true,
  'zai/glm-5.1': true,
  'zai/glm-5.2': ['high', 'max'],
  'zai/glm-5v-turbo': true,
  'nvidia/abacusai/dracarys-llama-3_1-70b-instruct': false,
  'nvidia/baai/bge-m3': false,
  'nvidia/black-forest-labs/flux_1-kontext-dev': false,
  'nvidia/black-forest-labs/flux_1-schnell': false,
  'nvidia/black-forest-labs/flux_2-klein-4b': false,
  'nvidia/black-forest-labs/flux.1-dev': false,
  'nvidia/bytedance/seed-oss-36b-instruct': false,
  'nvidia/deepseek-ai/deepseek-v4-flash': ['high', 'max'],
  'nvidia/deepseek-ai/deepseek-v4-pro': ['high', 'max'],
  'nvidia/google/gemma-2-2b-it': false,
  'nvidia/google/gemma-3n-e2b-it': false,
  'nvidia/google/gemma-3n-e4b-it': false,
  'nvidia/google/gemma-4-31b-it': true,
  'nvidia/google/google-paligemma': false,
  'nvidia/meta/esm2-650m': false,
  'nvidia/meta/esmfold': false,
  'nvidia/meta/llama-3.1-70b-instruct': false,
  'nvidia/meta/llama-3.1-8b-instruct': false,
  'nvidia/meta/llama-3.2-11b-vision-instruct': false,
  'nvidia/meta/llama-3.2-1b-instruct': false,
  'nvidia/meta/llama-3.2-3b-instruct': false,
  'nvidia/meta/llama-3.2-90b-vision-instruct': false,
  'nvidia/meta/llama-3.3-70b-instruct': false,
  'nvidia/meta/llama-4-maverick-17b-128e-instruct': false,
  'nvidia/meta/llama-guard-4-12b': false,
  'nvidia/microsoft/phi-4-mini-instruct': false,
  'nvidia/microsoft/phi-4-multimodal-instruct': false,
  'nvidia/minimaxai/minimax-m2.7': true,
  'nvidia/minimaxai/minimax-m3': true,
  'nvidia/mistralai/magistral-small-2506': false,
  'nvidia/mistralai/mistral-7b-instruct-v03': false,
  'nvidia/mistralai/mistral-large-3-675b-instruct-2512': false,
  'nvidia/mistralai/mistral-medium-3-instruct': false,
  'nvidia/mistralai/mistral-nemotron': false,
  'nvidia/mistralai/mistral-small-4-119b-2603': ['high'],
  'nvidia/mistralai/mixtral-8x22b-instruct': false,
  'nvidia/mistralai/mixtral-8x7b-instruct': false,
  'nvidia/moonshotai/kimi-k2-instruct-0905': false,
  'nvidia/moonshotai/kimi-k2.6': ['minimal', 'low', 'medium', 'high', 'xhigh', 'max'],
  'nvidia/nvidia/active-speaker-detection': false,
  'nvidia/nvidia/bevformer': false,
  'nvidia/nvidia/cosmos-predict1-5b': false,
  'nvidia/nvidia/cosmos-transfer1-7b': false,
  'nvidia/nvidia/cosmos-transfer2_5-2b': false,
  'nvidia/nvidia/gliner-pii': false,
  'nvidia/nvidia/llama-3_1-nemotron-safety-guard-8b-v3': false,
  'nvidia/nvidia/llama-3_2-nemoretriever-300m-embed-v1': false,
  'nvidia/nvidia/llama-nemotron-embed-vl-1b-v2': false,
  'nvidia/nvidia/llama-nemotron-rerank-vl-1b-v2': false,
  'nvidia/nvidia/magpie-tts-zeroshot': false,
  'nvidia/nvidia/nemotron-3-content-safety': false,
  'nvidia/nvidia/nemotron-3-nano-30b-a3b': true,
  'nvidia/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning': true,
  'nvidia/nvidia/nemotron-3-super-120b-a12b': true,
  'nvidia/nvidia/nemotron-3-ultra-550b-a55b': true,
  'nvidia/nvidia/nemotron-content-safety-reasoning-4b': true,
  'nvidia/nvidia/nemotron-mini-4b-instruct': false,
  'nvidia/nvidia/nemotron-voicechat': false,
  'nvidia/nvidia/nv-embed-v1': false,
  'nvidia/nvidia/nv-embedcode-7b-v1': false,
  'nvidia/nvidia/nvidia-nemotron-nano-9b-v2': true,
  'nvidia/nvidia/rerank-qa-mistral-4b': false,
  'nvidia/nvidia/riva-translate-4b-instruct-v1_1': false,
  'nvidia/nvidia/sparsedrive': false,
  'nvidia/nvidia/streampetr': false,
  'nvidia/nvidia/studiovoice': false,
  'nvidia/nvidia/synthetic-video-detector': false,
  'nvidia/nvidia/usdcode': false,
  'nvidia/nvidia/usdvalidate': false,
  'nvidia/openai/gpt-oss-120b': ['low', 'medium', 'high'],
  'nvidia/openai/gpt-oss-20b': ['low', 'medium', 'high'],
  'nvidia/openai/whisper-large-v3': false,
  'nvidia/qwen/qwen-image': false,
  'nvidia/qwen/qwen-image-edit': false,
  'nvidia/qwen/qwen2.5-coder-32b-instruct': false,
  'nvidia/qwen/qwen3-coder-480b-a35b-instruct': false,
  'nvidia/qwen/qwen3-next-80b-a3b-instruct': false,
  'nvidia/qwen/qwen3.5-122b-a10b': true,
  'nvidia/qwen/qwen3.5-397b-a17b': true,
  'nvidia/sarvamai/sarvam-m': false,
  'nvidia/stepfun-ai/step-3.5-flash': ['low', 'medium', 'high'],
  'nvidia/stepfun-ai/step-3.7-flash': ['minimal', 'low', 'medium', 'high', 'xhigh', 'max'],
  'nvidia/upstage/solar-10_7b-instruct': false,
  'nvidia/z-ai/glm-5.2': true,
  'huggingface/deepseek-ai/DeepSeek-R1': true,
  'huggingface/deepseek-ai/DeepSeek-R1-0528': true,
  'huggingface/deepseek-ai/DeepSeek-V3.2': true,
  'huggingface/deepseek-ai/DeepSeek-V4-Flash': true,
  'huggingface/deepseek-ai/DeepSeek-V4-Pro': ['high'],
  'huggingface/google/gemma-4-26B-A4B-it': true,
  'huggingface/google/gemma-4-31B-it': true,
  'huggingface/meta-llama/Llama-3.3-70B-Instruct': false,
  'huggingface/MiniMaxAI/MiniMax-M2': true,
  'huggingface/MiniMaxAI/MiniMax-M2.1': true,
  'huggingface/MiniMaxAI/MiniMax-M2.5': true,
  'huggingface/MiniMaxAI/MiniMax-M2.7': true,
  'huggingface/MiniMaxAI/MiniMax-M3': true,
  'huggingface/moonshotai/Kimi-K2-Instruct': false,
  'huggingface/moonshotai/Kimi-K2-Instruct-0905': false,
  'huggingface/moonshotai/Kimi-K2-Thinking': true,
  'huggingface/moonshotai/Kimi-K2.5': true,
  'huggingface/moonshotai/Kimi-K2.6': true,
  'huggingface/moonshotai/Kimi-K2.7-Code': true,
  'huggingface/openai/gpt-oss-120b': ['low', 'medium', 'high'],
  'huggingface/openai/gpt-oss-20b': ['low', 'medium', 'high'],
  'huggingface/Qwen/Qwen3-235B-A22B': true,
  'huggingface/Qwen/Qwen3-235B-A22B-Thinking-2507': true,
  'huggingface/Qwen/Qwen3-32B': true,
  'huggingface/Qwen/Qwen3-Coder-30B-A3B-Instruct': false,
  'huggingface/Qwen/Qwen3-Coder-480B-A35B-Instruct': false,
  'huggingface/Qwen/Qwen3-Coder-Next': false,
  'huggingface/Qwen/Qwen3-Embedding-4B': false,
  'huggingface/Qwen/Qwen3-Embedding-8B': false,
  'huggingface/Qwen/Qwen3-Next-80B-A3B-Instruct': false,
  'huggingface/Qwen/Qwen3-Next-80B-A3B-Thinking': false,
  'huggingface/Qwen/Qwen3.5-122B-A10B': true,
  'huggingface/Qwen/Qwen3.5-27B': true,
  'huggingface/Qwen/Qwen3.5-35B-A3B': true,
  'huggingface/Qwen/Qwen3.5-397B-A17B': ['low', 'medium', 'high'],
  'huggingface/Qwen/Qwen3.5-9B': true,
  'huggingface/Qwen/Qwen3.6-27B': true,
  'huggingface/Qwen/Qwen3.6-35B-A3B': true,
  'huggingface/stepfun-ai/Step-3.5-Flash': true,
  'huggingface/stepfun-ai/Step-3.7-Flash': ['low', 'medium', 'high'],
  'huggingface/XiaomiMiMo/MiMo-V2-Flash': true,
  'huggingface/XiaomiMiMo/MiMo-V2.5-Pro': true,
  'huggingface/zai-org/GLM-4.5': true,
  'huggingface/zai-org/GLM-4.5-Air': true,
  'huggingface/zai-org/GLM-4.5V': true,
  'huggingface/zai-org/GLM-4.6': true,
  'huggingface/zai-org/GLM-4.7': true,
  'huggingface/zai-org/GLM-4.7-Flash': true,
  'huggingface/zai-org/GLM-5': true,
  'huggingface/zai-org/GLM-5.1': true,
  'huggingface/zai-org/GLM-5.2': true,
  'baseten/deepseek-ai/DeepSeek-V3.1': true,
  'baseten/deepseek-ai/DeepSeek-V4-Pro': ['low', 'medium', 'high', 'xhigh'],
  'baseten/MiniMaxAI/MiniMax-M2.5': true,
  'baseten/moonshotai/Kimi-K2.5': true,
  'baseten/moonshotai/Kimi-K2.6': true,
  'baseten/moonshotai/Kimi-K2.7-Code': true,
  'baseten/nvidia/Nemotron-120B-A12B': true,
  'baseten/nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B': true,
  'baseten/openai/gpt-oss-120b': ['low', 'medium', 'high'],
  'baseten/zai-org/GLM-4.7': true,
  'baseten/zai-org/GLM-5': true,
  'baseten/zai-org/GLM-5.1': true,
  'baseten/zai-org/GLM-5.2': true,
  'ollama-cloud/cogito-2.1:671b': true,
  'ollama-cloud/deepseek-v3.1:671b': true,
  'ollama-cloud/deepseek-v3.2': true,
  'ollama-cloud/deepseek-v4-flash': ['high', 'max'],
  'ollama-cloud/deepseek-v4-pro': ['high', 'max'],
  'ollama-cloud/devstral-2:123b': false,
  'ollama-cloud/devstral-small-2:24b': false,
  'ollama-cloud/gemini-3-flash-preview': true,
  'ollama-cloud/gemma3:12b': false,
  'ollama-cloud/gemma3:27b': false,
  'ollama-cloud/gemma3:4b': false,
  'ollama-cloud/gemma4:31b': true,
  'ollama-cloud/glm-4.6': true,
  'ollama-cloud/glm-4.7': true,
  'ollama-cloud/glm-5': true,
  'ollama-cloud/glm-5.1': true,
  'ollama-cloud/glm-5.2': ['high', 'max'],
  'ollama-cloud/gpt-oss:120b': ['low', 'medium', 'high'],
  'ollama-cloud/gpt-oss:20b': ['low', 'medium', 'high'],
  'ollama-cloud/kimi-k2-thinking': true,
  'ollama-cloud/kimi-k2:1t': false,
  'ollama-cloud/kimi-k2.5': true,
  'ollama-cloud/kimi-k2.6': true,
  'ollama-cloud/kimi-k2.7-code': true,
  'ollama-cloud/minimax-m2': true,
  'ollama-cloud/minimax-m2.1': true,
  'ollama-cloud/minimax-m2.5': true,
  'ollama-cloud/minimax-m2.7': true,
  'ollama-cloud/minimax-m3': ['low', 'medium', 'high', 'max'],
  'ollama-cloud/ministral-3:14b': false,
  'ollama-cloud/ministral-3:3b': false,
  'ollama-cloud/ministral-3:8b': false,
  'ollama-cloud/mistral-large-3:675b': false,
  'ollama-cloud/nemotron-3-nano:30b': true,
  'ollama-cloud/nemotron-3-super': true,
  'ollama-cloud/nemotron-3-ultra': true,
  'ollama-cloud/qwen3-coder-next': false,
  'ollama-cloud/qwen3-coder:480b': false,
  'ollama-cloud/qwen3-next:80b': true,
  'ollama-cloud/qwen3-vl:235b': true,
  'ollama-cloud/qwen3-vl:235b-instruct': false,
  'ollama-cloud/qwen3.5:397b': true,
  'ollama-cloud/rnj-1:8b': false,
  'github-copilot/claude-fable-5': ['low', 'medium', 'high', 'xhigh', 'max'],
  'github-copilot/claude-haiku-4.5': true,
  'github-copilot/claude-opus-4.5': true,
  'github-copilot/claude-opus-4.6': ['low', 'medium', 'high', 'max'],
  'github-copilot/claude-opus-4.7': ['low', 'medium', 'high', 'xhigh', 'max'],
  'github-copilot/claude-opus-4.8': ['low', 'medium', 'high', 'xhigh', 'max'],
  'github-copilot/claude-sonnet-4': true,
  'github-copilot/claude-sonnet-4.5': true,
  'github-copilot/claude-sonnet-4.6': ['low', 'medium', 'high', 'max'],
  'github-copilot/claude-sonnet-5': ['low', 'medium', 'high', 'xhigh', 'max'],
  'github-copilot/gemini-2.5-pro': true,
  'github-copilot/gemini-3-flash-preview': ['low', 'medium', 'high'],
  'github-copilot/gemini-3.1-pro-preview': ['low', 'medium', 'high'],
  'github-copilot/gemini-3.5-flash': ['minimal', 'low', 'medium', 'high'],
  'github-copilot/gpt-4.1': false,
  'github-copilot/gpt-5-mini': ['low', 'medium', 'high'],
  'github-copilot/gpt-5.2': true,
  'github-copilot/gpt-5.2-codex': true,
  'github-copilot/gpt-5.3-codex': ['low', 'medium', 'high', 'xhigh'],
  'github-copilot/gpt-5.4': ['low', 'medium', 'high', 'xhigh'],
  'github-copilot/gpt-5.4-mini': ['low', 'medium', 'high', 'xhigh'],
  'github-copilot/gpt-5.4-nano': true,
  'github-copilot/gpt-5.5': ['low', 'medium', 'high', 'xhigh'],
  'github-copilot/gpt-5.6-luna': ['low', 'medium', 'high', 'xhigh', 'max'],
  'github-copilot/gpt-5.6-sol': ['low', 'medium', 'high', 'xhigh', 'max'],
  'github-copilot/gpt-5.6-terra': ['low', 'medium', 'high', 'xhigh', 'max'],
  'github-copilot/kimi-k2.7-code': true,
  'github-copilot/mai-code-1-flash-picker': ['low', 'medium', 'high'],
};
